[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
name = "integrationtest"
description = "A framework for pytest-based integration tests of DUNE-DAQ software"
version = "3.5.0"
readme = "docs/README.md"
requires-python = ">=3.6"
dependencies = [
    "h5py",
    "num2words",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
integrationtest = ["*"]

[project.entry-points."pytest11"]
name_of_plugin = "integrationtest.integrationtest_commandline"

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "pytest-cov",
]

[tool.pytest.ini_options]
addopts = "-v --tb=short --cov=integrationtest --cov=src/integrationtest tests/"  # omit --cov-report=html to avoid suppressing table to stdout

[tool.coverage.run]
source = ["integrationtest"]
omit = ["tests/*", "scripts/*"]
