import pytest
import os
import re
import pathlib
import integrationtest.data_classes as data_classes
from integrationtest.verbosity_helper import IntegtestVerbosityLevels

import functools
print = functools.partial(print, flush=True)  # always flush print() output


def basic_checks(run_dunerc, caplog, print_test_name: bool = True):

    # print out the name of the current test, if requested
    if print_test_name and run_dunerc.verbosity_helper.compare_level(IntegtestVerbosityLevels.drunc_transitions):
        # print the name of the current test
        current_test = os.environ.get("PYTEST_CURRENT_TEST")
        match_obj = re.search(r".*\[(.+)-run_.*rc.*\d\].*", current_test)
        if match_obj:
            current_test = match_obj.group(1)
        banner_line = re.sub(".", "=", current_test)
        print(banner_line)
        print(current_test)
        print(banner_line)

    # Check that dunerc completed correctly
    if run_dunerc.completed_process.returncode != 0:
        fail_msg = f"The run control session returned a non-zero status code ({run_dunerc.completed_process.returncode})."
        pytest.fail(fail_msg, pytrace=False)

    # Check that there weren't any warnings or errors during setup
    setup_logs = caplog.get_records("setup")
    if len(setup_logs) > 0:
        fail_msg = f"One or more problems were encountered during the setup of the pytest: {setup_logs}"
        pytest.fail(fail_msg, pytrace=False)


def delete_file(file: pathlib.PosixPath, verbose: bool = False):
    try:
      file.unlink()
      if verbose:
          print(f"File {file} was successfully deleted.")
    except FileNotFoundError:
      print(f"File {file} could not be deleted because it was not found.")
    except IsADirectoryError:
      print(f"File {file} could not be deleted because it is actually a directory.")


# ************************************************************
# Enable the FakeHSI trigger and optionally set some of its parameters.
# - Note that this function can currently only be called with integtest parameters
#   that request a _generated_ DUNE-DAQ configuration.
# - Note that enabling the FakeHSI trigger in generated DUNE-DAQ configurations currently
#   disables the generation of DUNE-DAQ configuration for the RandomTriggerCandidateMaker.
#   (Not sure of the history of this choice; it is a feature of the 'generation' code.)
# ************************************************************
def enable_fake_hsi_trigger(integtest_params: data_classes.integtest_param_base_class, trigger_rate: float = None,
                            readout_window_before_ticks: int = None, readout_window_after_ticks: int = None):
    if not isinstance(integtest_params, data_classes.integtest_params_for_generated_dunedaq_config):
        fail_msg = ("The FakeHSI trigger can only be dynamically enabled in DUNE-DAQ "
                    "configurations that are generated by the integration test infrastructure, "
                    "not ones that are pre-defined.")
        pytest.fail(fail_msg, pytrace=False)

    integtest_params.fake_hsi_enabled = True
    set_fake_hsi_trigger_params(integtest_params, trigger_rate, readout_window_before_ticks, readout_window_after_ticks)


# ************************************************************
# Set values for one or more parameters associated with the FakeHSI trigger
# ************************************************************
def set_fake_hsi_trigger_params(integtest_params: data_classes.integtest_param_base_class, trigger_rate: float = None,
                                readout_window_before_ticks: int = None, readout_window_after_ticks: int = None):
    if trigger_rate is not None:
        integtest_params.config_substitutions.append(
            data_classes.attribute_substitution(
                obj_class="FakeHSIEventGeneratorConf",
                obj_id="fakehsi",
                updates={"trigger_rate": trigger_rate},
            )
        )

    readout_params = {}
    if readout_window_before_ticks is not None:
        readout_params["time_before"] = readout_window_before_ticks
    if readout_window_after_ticks is not None:
        readout_params["time_after"] = readout_window_after_ticks
    if readout_params:
        integtest_params.config_substitutions.append(
            data_classes.attribute_substitution(
                obj_class="TCReadoutMap",
                obj_id="def-hsi-tc-map",
                updates=readout_params,
            )
        )


# ************************************************************
# Set values for one or more parameters associated with the RandomTriggerCandidateMaker trigger.
# - Note that this function makes use of the DUNE-DAQ configuration parameters that are
#   available in the RTCM C++ code itself. It does *not* use the DUNE-DAQ configuration
#   parameters that are part of the TCReadoutMap. This is because the former has more
#   flexibility, for example the ability to set a backshift amount of time.
# - Currently, this function does *not* check if a TCReadoutMap entry for kRandom triggers
#   exists in the input/template DUNE-DAQ configuration, so there is the possibility of some
#   confusion if a kRandom TCReadoutMap entry exists.
# ************************************************************
def set_rtcm_trigger_params(integtest_params: data_classes.integtest_param_base_class, trigger_rate: float = None,
                            readout_window_before_ticks: int = None, readout_window_after_ticks: int = None,
                            readout_window_backshift_ticks: int = None):
    rtcm_params = {}
    if trigger_rate is not None:
        rtcm_params["trigger_rate_hz"] = trigger_rate
    if readout_window_before_ticks is not None:
        rtcm_params["candidate_window_before_ts"] = readout_window_before_ticks
    if readout_window_after_ticks is not None:
        rtcm_params["candidate_window_after_ts"] = readout_window_after_ticks
    if readout_window_backshift_ticks is not None:
        rtcm_params["candidate_backshift_ts"] = readout_window_backshift_ticks

    if rtcm_params:
        integtest_params.config_substitutions.append(
            data_classes.attribute_substitution(
                obj_class="RandomTCMakerConf",
                obj_id="random-tc-generator",
                updates=rtcm_params,
            )
        )
